# Uncomment the next line to define a global platform for your project

platform :ios, '14.0'
inhibit_all_warnings!

abstract_target 'ONETHING_iOS' do
  use_frameworks!

  pod 'KakaoSDKUser'
  pod 'SnapKit', '~> 5.0.0'
  pod 'RxSwift', '6.2.0'
  pod 'RxCocoa', '6.2.0'
  pod 'Moya', '~> 14.0'

  target 'ONETHING_iOS Beta' do
  end

  target 'ONETHING_iOS Ent' do
  end

  target 'ONETHING_iOSTests' do
    inherit! :search_paths
  end

  target 'ONETHING_iOSUITests' do
  end

end