# Uncomment the next line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '14.0'
inhibit_all_warnings!

abstract_target 'ONETHING_iOS' do
  use_frameworks!

  pod 'KakaoSDKUser'
  pod 'SnapKit', '~> 5.0.0'
  pod 'RxSwift', '6.2.0'
  pod 'RxCocoa', '6.2.0'
  pod 'Moya', '~> 14.0'
  pod 'Alamofire'
  pod 'Kingfisher', '~> 6.0'
  pod 'ActiveLabel'
  pod 'Then'
  pod 'Carte'
  pod 'lottie-ios'

  target 'ONETHING' do
  end

  target 'ONETHING Beta' do
  end

  target 'ONETHING Ent' do
  end

  target 'ONETHING_iOSTests' do
  end

  target 'ONETHING_iOSUITests' do
  end

end
