# Uncomment the next line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '14.0'
inhibit_all_warnings!

abstract_target 'ONETHING_iOS' do
  use_frameworks!

  pod 'KakaoSDKUser', '~> 2.11.1'
  pod 'SnapKit', '~> 5.0.0'
  pod 'RxSwift', '~> 6.5.0'
  pod 'RxCocoa', '~> 6.5.0'
  pod 'Moya', '~> 14.0'
  pod 'Alamofire', '~> 5.4.3' 
  pod 'Kingfisher', '~> 7.0'
  pod 'ActiveLabel'
  pod 'Toaster'
  pod 'Then'
  pod 'Carte'
  pod 'lottie-ios'

  target 'ONETHING' do
  end

  target 'ONETHING Beta' do
  end

  target 'ONETHING Ent' do
  end

  target 'ONETHING_iOSTests' do
  end

  target 'ONETHING_iOSUITests' do
  end

end
